### PR TITLE
Configuring the core MVC middleware only when calling AddApiVersioning

### PR DESCRIPTION
**Pull request by denisivan0v**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/aspnet-api-versioning/74)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Related to #66

**Comment by commonsensesoftware** [comment]
I didn't forget about your PR. I'm having trouble with setting up the CLA service (which is required). Boo - rules. Shame on me for not getting that setup months ago.

I'm working on a few other related updates.  Since the change appears to only require a single method call change, I'll likely just incorporate this modification manually.  I do appreciate the help though. Spasiba!

**Comment by denisivan0v** [comment]
You're welcome, always glad to help! I'll wait for updates to use them in my apps

**Comment by commonsensesoftware** [comment]
The code was right, but there were a few other references that needed to be updated. I'm closing this PR since the actual change will occur in PR #92. You can see the exact changes in commit [448f02e](../pull/92/commits/448f02eba2ca39a391ce0bad991573ce97956f81).

I also have the CLA requirements properly set up now, which will enable me to easily accept future contributions from the community. Thanks again for your help.

**Pull request closed without merging**
